### ISSUE TITLE
Error unpacking BIOS zips

### ISSUE THREAD

**Issue by wizzomafizzo** [MiSTer-devel/Downloader_MiSTer#23]
I'm on a fresh install and I am getting this error during the BiosDB step (in update_all):

```
Extracting NeoGeo UniBios from http://unibios.free.fr
checkdir:  cannot create extraction directory: /tmp/q48as6j6/neogeo_unibios
           No such file or directory
Traceback (most recent call last):
  File "/tmp/dont_download.zip/downloader/main.py", line 37, in main
    exit_code = execute_full_run(
  File "/tmp/dont_download.zip/downloader/main.py", line 57, in execute_full_run
    exit_code = runner.full_run()
  File "/tmp/dont_download.zip/downloader/full_run_service.py", line 59, in full_run
    result = self._full_run_impl()
  File "/tmp/dont_download.zip/downloader/full_run_service.py", line 121, in _full_run_impl
    self._online_importer.download_dbs_contents(importer_command, full_resync)
  File "/tmp/dont_download.zip/downloader/online_importer.py", line 95, in download_dbs_contents
    db_importer.process_changed_files(changed_files, needed_zips, filtered_zip_data)
  File "/tmp/dont_download.zip/downloader/online_importer.py", line 586, in process_changed_files
    self._import_zip_contents(needed_zips, filtered_zip_data, file_downloader)
  File "/tmp/dont_download.zip/downloader/online_importer.py", line 672, in _import_zip_contents
    self._file_system.unzip_contents(temp_zip, tmp_path, list(zipped_files['files']))
  File "/tmp/dont_download.zip/downloader/file_system.py", line 335, in unzip_contents
    raise Exception("Could not unzip %s: %s" % (file, result.returncode))
Exception: Could not unzip /tmp/hir0qr7h_neogeo_unibios_contents.zip: 2
```

I think the parent tmp directory isn't being created after the name is generated?

https://github.com/MiSTer-devel/Downloader_MiSTer/blob/0060984366a335546a7152ff83065c729d962d83/src/downloader/online_importer.py#L671

**Comment by theypsilon** [comment]
Hey! It was a problem with 'extract-single-files' feature that I've just fixed, please try again in 10 minutes (now it's building), and let me know if the problem went away.

**Comment by wizzomafizzo** [comment]
It works! Thanks mate, talk about service
