### ISSUE TITLE
 Invalid cross-device link on update

### ISSUE THREAD

**Issue by KClough** [MiSTer-devel/Downloader_MiSTer#24]
```
Copying new MiSTer binary:
Traceback (most recent call last):
  File "/tmp/dont_download.zip/downloader/main.py", line 37, in main
    exit_code = execute_full_run(
  File "/tmp/dont_download.zip/downloader/main.py", line 57, in execute_full_run
    exit_code = runner.full_run()
  File "/tmp/dont_download.zip/downloader/full_run_service.py", line 59, in full_run
    result = self._full_run_impl()
  File "/tmp/dont_download.zip/downloader/full_run_service.py", line 121, in _full_run_impl
    self._online_importer.download_dbs_contents(importer_command, full_resync)
  File "/tmp/dont_download.zip/downloader/online_importer.py", line 95, in download_dbs_contents
    db_importer.process_changed_files(changed_files, needed_zips, filtered_zip_data)
  File "/tmp/dont_download.zip/downloader/online_importer.py", line 588, in process_changed_files
    file_downloader.download_files(self._is_first_run())
  File "/tmp/dont_download.zip/downloader/file_downloader.py", line 121, in download_files
    self._file_system.move(FILE_MiSTer_new, FILE_MiSTer)
  File "/tmp/dont_download.zip/downloader/file_system.py", line 189, in move
    os.replace(self._path(source), self._path(target))
OSError: [Errno 18] Invalid cross-device link: '/media/usb0/MiSTer.new' -> '/media/fat/MiSTer'

Downloader failed!
```

Here is my `download.ini`

```
[MiSTer]
base_path = '/media/usb0'

[distribution_mister]
db_url = https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/main/db.json.zip

[jtcores]
db_url = https://raw.githubusercontent.com/jotego/jtcores_mister/main/jtbindb.json.zip

[bios_db]
db_url = https://raw.githubusercontent.com/theypsilon/BiosDB_MiSTer/db/bios_db.json
```

**Comment by theypsilon** [comment]
More instances of seemlingly looking similar issues: https://misterfpga.org/viewtopic.php?t=4741

I've tried to reproduce it many times without success yet.

**Comment by theypsilon** [comment]
More instances: https://misterfpga.org/viewtopic.php?p=64698#p64698

**Comment by theypsilon** [comment]
Is anyone having this issue lately? I think I might have fixed it a while ago.

**Comment by Fuuj0r** [comment]
I have just started having the issue, seems to be with the mister distribution part

START!

Reading file: /media/fat/downloader.ini
Reading 'distribution_mister' db section
Reading 'jtcores' db section
Reading 'Coin-OpCollection/Distribution-MiSTerFPGA' db section
Reading 'mrext/all' db section
Reading 'names_txt' db section
Reading 'arcade_names_txt' db section
Reading 'bios_db' db section
Reading 'arcade_roms_db' db section
Reading 'theypsilon_unofficial_distribution' db section
Reading 'agg23_db' db section
env: {
    "DOWNLOADER_LAUNCHER_PATH": null,
    "DOWNLOADER_INI_PATH": "/media/fat/downloader.ini",
    "LOGFILE": null,
    "CURL_SSL": "--cacert /etc/ssl/certs/cacert.pem",
    "COMMIT": "f84d696",
    "ALLOW_REBOOT": "0",
    "UPDATE_LINUX": "false",
    "DEFAULT_DB_URL": "https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/main/db.json.zip",
    "DEFAULT_DB_ID": "distribution_mister",
    "DEFAULT_BASE_PATH": null,
    "FORCED_BASE_PATH": null,
    "PC_LAUNCHER": null,
    "DEBUG": "false",
    "FAIL_ON_FILE_ERROR": "false"
}
config: {
    "databases": {
        "distribution_mister": {
            "db_url": "https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/main/db.json.zip",
            "section": "distribution_mister"
        },
        "jtcores": {
            "db_url": "https://raw.githubusercontent.com/jotego/jtcores_mister/main/jtbindb.json.zip",
            "section": "jtcores"
        },
        "coin-opcollection/distribution-misterfpga": {
            "db_url": "https://raw.githubusercontent.com/Coin-OpCollection/Distribution-MiSTerFPGA/db/db.json.zip",
            "section": "coin-opcollection/distribution-misterfpga"
        },
        "mrext/all": {
            "db_url": "https://raw.githubusercontent.com/wizzomafizzo/mrext/main/releases/all.json",
            "section": "mrext/all"
        },
        "names_txt": {
            "db_url": "https://raw.githubusercontent.com/ThreepwoodLeBrush/Names_MiSTer/dbs/names_CHAR18_Common_JP.json",
            "section": "names_txt"
        },
        "arcade_names_txt": {
            "db_url": "https://raw.githubusercontent.com/PigSaint/ArcadeNames_MiSTer/dbs/arcade_names_JP.json",
            "section": "arcade_names_txt"
        },
        "bios_db": {
            "db_url": "https://raw.githubusercontent.com/BigDendy/BiosDB_MiSTer/db/bios_db.json.zip",
            "section": "bios_db"
        },
        "arcade_roms_db": {
            "db_url": "https://raw.githubusercontent.com/BigDendy/ArcadeROMsDB_MiSTer/db/arcade_roms_db.json.zip",
            "section": "arcade_roms_db"
        },
        "theypsilon_unofficial_distribution": {
            "db_url": "https://raw.githubusercontent.com/theypsilon/Distribution_Unofficial_MiSTer/main/unofficialdb.json.zip",
            "section": "theypsilon_unofficial_distribution"
        },
        "agg23_db": {
            "db_url": "https://raw.githubusercontent.com/agg23/mister-repository/db/manifest.json",
            "section": "agg23_db"
        }
    },
    "config_path": "/media/fat/downloader.ini",
    "base_path": "/media/fat",
    "base_system_path": "/media/fat",
    "storage_priority": "prefer_external",
    "allow_delete": 1,
    "allow_reboot": 0,
    "update_linux": false,
    "downloader_threads_limit": 20,
    "downloader_timeout": 300,
    "downloader_retries": 3,
    "zip_file_count_threshold": 60,
    "zip_accumulated_mb_threshold": 100,
    "filter": null,
    "verbose": false,
    "debug": false,
    "default_db_id": "distribution_mister",
    "start_time": 1706209102.8921897,
    "logfile": null,
    "is_pc_launcher": false,
    "user_defined_options": [
        "storage_priority"
    ],
    "commit": "f84d696",
    "fail_on_file_error": false,
    "minimum_system_free_space_mb": 512,
    "minimum_external_free_space_mb": 128,
    "curl_ssl": "--cacert /etc/ssl/certs/cacert.pem"
}
Reading file contents "/MiSTer.version"
Linux Version: 231108
cacert file at "/etc/ssl/certs/cacert.pem" seems to be fine.
Reading file contents "/proc/mounts"

Detected following connected drives:
/media/usb0

Loading dict from file "/media/usb0/.downloader_db.json"
Loading db from url: https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/main/db.json.zip
Loading db from url: https://raw.githubusercontent.com/jotego/jtcores_mister/main/jtbindb.json.zip
Loading db from url: https://raw.githubusercontent.com/Coin-OpCollection/Distribution-MiSTerFPGA/db/db.json.zip
Loading db from url: https://raw.githubusercontent.com/wizzomafizzo/mrext/main/releases/all.json
Loading db from url: https://raw.githubusercontent.com/ThreepwoodLeBrush/Names_MiSTer/dbs/names_CHAR18_Common_JP.json
Loading db from url: https://raw.githubusercontent.com/PigSaint/ArcadeNames_MiSTer/dbs/arcade_names_JP.json
Loading db from url: https://raw.githubusercontent.com/BigDendy/BiosDB_MiSTer/db/bios_db.json.zip
Loading db from url: https://raw.githubusercontent.com/BigDendy/ArcadeROMsDB_MiSTer/db/arcade_roms_db.json.zip
Loading db from url: https://raw.githubusercontent.com/theypsilon/Distribution_Unofficial_MiSTer/main/unofficialdb.json.zip
Loading db from url: https://raw.githubusercontent.com/agg23/mister-repository/db/manifest.json
/tmp/uhngmbtf
/tmp/0tkae5u0
/tmp/1g70fsgn
/tmp/lp00_vhc
/tmp/9p55ke6b
/tmp/e6e85urz
/tmp/u60k1hng
/tmp/i45lv7mh
/tmp/utdbkbl0
/tmp/qpbdaxgs
..........++++++++++
Loading dict from file "/tmp/uhngmbtf"
Removing "/tmp/uhngmbtf"
Loading dict from file "/tmp/0tkae5u0"
Removing "/tmp/0tkae5u0"
Loading dict from file "/tmp/1g70fsgn"
Removing "/tmp/1g70fsgn"
Loading dict from file "/tmp/lp00_vhc"
Removing "/tmp/lp00_vhc"
Loading dict from file "/tmp/9p55ke6b"
Removing "/tmp/9p55ke6b"
Loading dict from file "/tmp/e6e85urz"
Removing "/tmp/e6e85urz"
Loading dict from file "/tmp/u60k1hng"
Removing "/tmp/u60k1hng"
Loading dict from file "/tmp/i45lv7mh"
Removing "/tmp/i45lv7mh"
Loading dict from file "/tmp/utdbkbl0"
Removing "/tmp/utdbkbl0"
Loading dict from file "/tmp/qpbdaxgs"
Removing "/tmp/qpbdaxgs"
distribution_mister still uses base_path: /media/fat
jtcores still uses base_path: /media/fat
coin-opcollection/distribution-misterfpga still uses base_path: /media/fat
mrext/all still uses base_path: /media/fat
names_txt still uses base_path: /media/fat
arcade_names_txt still uses base_path: /media/fat
bios_db still uses base_path: /media/fat
arcade_roms_db still uses base_path: /media/fat
theypsilon_unofficial_distribution still uses base_path: /media/fat
agg23_db still uses base_path: /media/fat
Preparing databases ...
Preparing db 'distribution_mister'...
/tmp/kc2vf426_atari2600_palettes_summary.json.zip
/tmp/kc2vf426_atari7800_palettes_summary.json.zip
/tmp/kc2vf426_cheats_folder_gameboy_summary.json.zip
/tmp/kc2vf426_cheats_folder_gba_summary.json.zip
/tmp/kc2vf426_cheats_folder_megadrive_summary.json.zip
/tmp/kc2vf426_cheats_folder_nes_summary.json.zip
/tmp/kc2vf426_cheats_folder_psx_summary.json.zip
/tmp/kc2vf426_cheats_folder_sms_summary.json.zip
/tmp/kc2vf426_cheats_folder_snes_summary.json.zip
/tmp/kc2vf426_cheats_folder_tgfx16_summary.json.zip
/tmp/kc2vf426_cheats_folder_tgfx16-cd_summary.json.zip
/tmp/kc2vf426_gameboy2p_palettes_summary.json.zip
/tmp/kc2vf426_gameboy_palettes_summary.json.zip
/tmp/kc2vf426_gbc_palettes_summary.json.zip
/tmp/kc2vf426_global_filters_summary.json.zip
/tmp/kc2vf426_global_fonts_summary.json.zip
/tmp/kc2vf426_global_shadow_masks_summary.json.zip
/tmp/kc2vf426_megaduck_palettes_summary.json.zip
/tmp/kc2vf426_mra_alternatives_summary.json.zip
/tmp/kc2vf426_nes_palettes_summary.json.zip
....................++++++++++++++++++++
Loading dict from file "/tmp/kc2vf426_atari2600_palettes_summary.json.zip"
Removing "/tmp/kc2vf426_atari2600_palettes_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_atari7800_palettes_summary.json.zip"
Removing "/tmp/kc2vf426_atari7800_palettes_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_cheats_folder_gba_summary.json.zip"
Removing "/tmp/kc2vf426_cheats_folder_gba_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_cheats_folder_tgfx16_summary.json.zip"
Removing "/tmp/kc2vf426_cheats_folder_tgfx16_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_cheats_folder_gameboy_summary.json.zip"
Removing "/tmp/kc2vf426_cheats_folder_gameboy_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_cheats_folder_megadrive_summary.json.zip"
Removing "/tmp/kc2vf426_cheats_folder_megadrive_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_cheats_folder_snes_summary.json.zip"
Removing "/tmp/kc2vf426_cheats_folder_snes_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_cheats_folder_sms_summary.json.zip"
Removing "/tmp/kc2vf426_cheats_folder_sms_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_cheats_folder_nes_summary.json.zip"
Removing "/tmp/kc2vf426_cheats_folder_nes_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_cheats_folder_psx_summary.json.zip"
Removing "/tmp/kc2vf426_cheats_folder_psx_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_megaduck_palettes_summary.json.zip"
Removing "/tmp/kc2vf426_megaduck_palettes_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_cheats_folder_tgfx16-cd_summary.json.zip"
Removing "/tmp/kc2vf426_cheats_folder_tgfx16-cd_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_global_fonts_summary.json.zip"
Removing "/tmp/kc2vf426_global_fonts_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_gameboy2p_palettes_summary.json.zip"
Removing "/tmp/kc2vf426_gameboy2p_palettes_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_global_filters_summary.json.zip"
Removing "/tmp/kc2vf426_global_filters_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_gbc_palettes_summary.json.zip"
Removing "/tmp/kc2vf426_gbc_palettes_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_nes_palettes_summary.json.zip"
Removing "/tmp/kc2vf426_nes_palettes_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_gameboy_palettes_summary.json.zip"
Removing "/tmp/kc2vf426_gameboy_palettes_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_mra_alternatives_summary.json.zip"
Removing "/tmp/kc2vf426_mra_alternatives_summary.json.zip"
Loading dict from file "/tmp/kc2vf426_global_shadow_masks_summary.json.zip"
Removing "/tmp/kc2vf426_global_shadow_masks_summary.json.zip"
No filter for db distribution_mister.
Traceback (most recent call last):
  File "/tmp/tmpoduzm4ln/downloader/main.py", line 14, in main
    exit_code = execute_full_run(
  File "/tmp/tmpoduzm4ln/downloader/main.py", line 30, in execute_full_run
    exit_code = runner.full_run()
  File "/tmp/tmpoduzm4ln/downloader/full_run_service.py", line 34, in full_run
    result = self._full_run_impl()
  File "/tmp/tmpoduzm4ln/downloader/full_run_service.py", line 79, in _full_run_impl
    self._online_importer.download_dbs_contents(importer_command, full_resync)
  File "/tmp/tmpoduzm4ln/downloader/online_importer.py", line 42, in download_dbs_contents
    packages = self._unpack_dbs_data(importer_command, full_resync)
  File "/tmp/tmpoduzm4ln/downloader/online_importer.py", line 76, in _unpack_dbs_data
    file_system.precache_is_file_with_folders(resolved_db.folders.keys())
  File "/tmp/tmpoduzm4ln/downloader/file_system.py", line 117, in precache_is_file_with_folders
    return self._fs.precache_is_file_with_folders(folders)
  File "/tmp/tmpoduzm4ln/downloader/file_system.py", line 175, in precache_is_file_with_folders
    files = [f.path for f in os.scandir(full_folder_path) if f.is_file()]
  File "/tmp/tmpoduzm4ln/downloader/file_system.py", line 175, in <listcomp>
    files = [f.path for f in os.scandir(full_folder_path) if f.is_file()]
OSError: [Errno 5] Input/output error: '/media/usb0/games/Genesis'

**Comment by theypsilon** [comment]
It seems to be fixed.
