### ISSUE TITLE
ImportError: No module named '_ssl'

### ISSUE THREAD

**Issue by Grazfather** [MiSTer-devel/Downloader_MiSTer#30]
```python
/media/fat/Scripts# ./downloader.sh
Running MiSTer Downloader

Traceback (most recent call last):
  File "/home/user/work/fpga/DE10/buildroot-2017.02/output/target/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
  File "/home/user/work/fpga/DE10/buildroot-2017.02/output/target/usr/lib/python3.5/runpy.py", line 85, in _run_code
  File "/tmp/dont_download.zip/__main__.py", line 22, in <module>
  File "/tmp/dont_download.zip/downloader/main.py", line 27, in <module>
  File "/tmp/dont_download.zip/downloader/full_run_service_factory.py", line 22, in <module>
  File "/tmp/dont_download.zip/downloader/file_downloader.py", line 21, in <module>
  File "/home/user/work/fpga/DE10/buildroot-2017.02/output/target/usr/lib/python3.5/ssl.py", line 98, in <module>
ImportError: No module named '_ssl'
Downloader failed!
```

This is probably due to my mister linux install being old, but how to mitigate should probably be documented.

**Comment by theypsilon** [comment]
Thanks for reporting. Could you please verify that running it again displays a more readable error message?

(wait 5 minutes after the date of this message to give time for the content to update)

**Comment by Grazfather** [comment]
I actually happened to have already seen that message, while running update_all. I've since flashed mr. fusion, though, so can't repro anymore.

```bash
/media/fat/Scripts# ./update_all.sh
Launching Update All

invalid syntax (config.py, line 29)


Warning! Your OS version seems to be older than September 2021!
Please upgrade your OS before running Update All
More info at https://github.com/MiSTer-devel/mr-fusion

Update All failed!
```

If your change matches the condition in update_all, then I can confirm it should catch my particular issue, since update_all did give me the warning message.

**Comment by theypsilon** [comment]
Thanks for confirming

**Comment by Grazfather** [comment]
Thanks for the quick fix!
