### ISSUE TITLE
Stale file handle: '/media/fat/cifs/games/NEOGEO/gog-broken-romsets.xml'

### ISSUE THREAD

**Issue by aminta** [MiSTer-devel/Downloader_MiSTer#36]
Hi there! Tonight for the firs time the Downloader tool gave me an error:

```

Traceback (most recent call last):
  File "/tmp/tmpo0uv7a5w/downloader/main.py", line 37, in main
    exit_code = execute_full_run(
  File "/tmp/tmpo0uv7a5w/downloader/main.py", line 57, in execute_full_run
    exit_code = runner.full_run()
  File "/tmp/tmpo0uv7a5w/downloader/full_run_service.py", line 59, in full_run
    result = self._full_run_impl()
  File "/tmp/tmpo0uv7a5w/downloader/full_run_service.py", line 118, in _full_run_impl
    self._online_importer.download_dbs_contents(importer_command, full_resync)
  File "/tmp/tmpo0uv7a5w/downloader/online_importer.py", line 90, in download_dbs_contents
    changed_files, needed_zips = db_importer.select_changed_files()
  File "/tmp/tmpo0uv7a5w/downloader/online_importer.py", line 596, in select_changed_files
    if store_hash == 'file_does_not_exist_so_cant_get_hash' and self._file_system.hash(file_path) == file_description['hash']:
  File "/tmp/tmpo0uv7a5w/downloader/file_system.py", line 198, in hash
    return hash_file(self._path(path))
  File "/tmp/tmpo0uv7a5w/downloader/file_system.py", line 336, in hash_file
    with open(path, "rb") as f:
OSError: [Errno 116] Stale file handle: '/media/fat/cifs/games/NEOGEO/gog-broken-romsets.xml'

```

Downloader.ini:

```
[MiSTer]
; base_path is where most files will be installed
;   Useful for setups with USB storage, for example: '/media/usb0/'
base_path = '/media/fat/'

; base_system_path is where system files such as 'MiSTer' and 'menu.rbf' will be installed.
;   Warning: It is recommended to NOT change this setting regardless of your setup.
base_system_path = '/media/fat/'

; allow_delete options:
;   0 -> Don't allow this tool to delete anything at all.
;   1 -> Allow this tool to delete any old file from previous updates.
;   2 -> Allow this tool to delete only old cores that receive a new version.
allow_delete = 1

; allow_reboot options:
;   0 -> Don't allow this tool to ever reboot automatically.
;   1 -> Allow this tool to reboot the system after any system file has been updated.
;   2 -> Allow this tool to reboot the system only after Linux has been updated.
allow_reboot = 1

; update_linux options:
;   true -> Updates Linux when there is a new update (very recommended).
;   false -> Doesn't update Linux.
update_linux = true

; parallel_update options:
;   true -> Tries to more than one file simultaneously.
;   false -> Will only download one file at a time.
parallel_update = true

; downloader_timeout: Can be tweaked to increase the timeout time in seconds
;   It is useful to increase this value for users with slow connections.
downloader_timeout = 300

; downloader_retries: Can be tweaked to increase the retries per failed download
;   It is useful to increase this value for users with very unstable connections.
downloader_retries = 3

[jtcores]
db_url = https://raw.githubusercontent.com/jotego/jtcores_mister/main/jtbindb.json.zip
filter = [MiSTer]

[distribution_mister]
db_url = https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/main/db.json.zip

[bios_db]
db_url = https://raw.githubusercontent.com/theypsilon/BiosDB_MiSTer/db/bios_db.json

[mrext/all]
db_url = https://github.com/wizzomafizzo/mrext/raw/main/releases/all.json

[theypsilon_unofficial_distribution]
db_url = https://raw.githubusercontent.com/theypsilon/Distribution_Unofficial_MiSTer/main/unofficialdb.json.zip

[names_txt]
db_url = https://raw.githubusercontent.com/ThreepwoodLeBrush/Names_MiSTer/dbs/names_CHAR18_Common_EU.json

[tty2oled_files]
db_url = https://raw.githubusercontent.com/venice1200/MiSTer_tty2oled/main/tty2oleddb.json

[atrac17/Coin-Op_Collection]
db_url = https://raw.githubusercontent.com/atrac17/Coin-Op_Collection/db/db.json.zip

[arcade_roms_db]
db_url = https://raw.githubusercontent.com/theypsilon/ArcadeROMsDB_MiSTer/db/arcade_roms_db.json.zip

[arcade_offset_folder]
db_url = https://raw.githubusercontent.com/atrac17/Arcade_Offset/db/arcadeoffsetdb.json.zip

[favorites]
db_url = https://raw.githubusercontent.com/wizzomafizzo/MiSTer_Favorites/main/favorites.json

[rgarcialago/video_presets_by_robby]
db_url = https://raw.githubusercontent.com/RGarciaLago/VIDEO_PRESETS_by_Robby/db/db.json.zip

[ajgowans/wip]
db_url = https://raw.githubusercontent.com/ajgowans/wip/db/db.json.zip

[agg23_db]
db_url = https://github.com/agg23/mister-repository/raw/db/manifest.json


```

update_all.log:

```
env: {
    "CURL_SSL": "--cacert /etc/ssl/certs/cacert.pem",
    "COMMIT": "5ecc39f",
    "LOCATION_STR": "MiSTer",
    "DEBUG": "false",
    "KEY_IGNORE_TIME": "0.1",
    "TRANSITION_SERVICE_ONLY": "false"
}
config: {
    "start_time": 1691179947.4712405,
    "has_jtpremium": false,
    "has_mistersam_main_branch": false,
    "curl_ssl": "--cacert /etc/ssl/certs/cacert.pem",
    "commit": "5ecc39f",
    "key_ignore_time": 0.1,
    "base_path": "/media/fat/",
    "base_system_path": "/media/fat/",
    "paths_from_downloader_ini": true,
    "update_linux": true,
    "not_mister": false,
    "verbose": false,
    "temporary_downloader_ini": false,
    "transition_service_only": 0,
    "databases": "{'mrext/all', 'distribution_mister', 'atrac17/Coin-Op_Collection', 'arcade_offset_folder', 'tty2oled_files', 'jtcores', 'bios_db', 'agg23_db', 'names_txt', 'theypsilon_unofficial_distribution', 'arcade_roms_db'}",
    "arcade_organizer": true,
    "encc_forks": false,
    "download_beta_cores": true,
    "names_region": "EU",
    "names_char_code": "CHAR18",
    "names_sort_code": "Common",
    "hbmame_filter": false,
    "rannysnice_wallpapers_filter": "ar16-9",
    "wait_time_for_reading": 2,
    "countdown_time": 15,
    "autoreboot": true,
    "main_updater": true,
    "jotego_updater": true,
    "names_txt_updater": true,
    "bios_getter": true,
    "arcade_roms_db_downloader": true,
    "unofficial_updater": true,
    "llapi_updater": false,
    "arcade_offset_downloader": true,
    "coin_op_collection_downloader": true,
    "agg23_db": true,
    "MikeS11/YC_Builds-MiSTer": false,
    "tty2oled_files_downloader": true,
    "i2c2oled_files_downloader": false,
    "mistersam_files_downloader": false,
    "mrext/all": true,
    "Ranny-Snice/Ranny-Snice-Wallpapers": false
}
store: {
    "migration_version": 0,
    "theme": "Blue Installer",
    "wait_time_for_reading": 2,
    "countdown_time": 15,
    "autoreboot": true,
    "download_beta_cores": true,
    "names_region": "EU",
    "names_char_code": "CHAR18",
    "names_sort_code": "Common"
}

                        -------- Update All 2.0 ---------                        
                        The All-in-One Updater for MiSTer
                        ---------------------------------
                          - Powered by Downloader 1.7 -


                    ╔═══════════════════════════════════════╗                   
                    ║  Thank you so much for your support!  ║                   
                    ╚═══════════════════════════════════════╝                   

Reading sections from /media/fat/downloader.ini

Sequence:
- Main Distribution: MiSTer-devel
- JTCORES for MiSTer (+betas)
- Names TXT: CHAR18 Common EU
- BIOS Database
- Arcade ROMs Database
- theypsilon Unofficial Distribution
- Arcade Offset folder
- Coin-Op Collection
- agg23's MiSTer Cores
- tty2oled files
- MiSTer Extensions (wizzo)
- Arcade Organizer


 [1m*[0mPress <[1mUP[0m>, To enter the SETTINGS screen.
 [1m*[0mPress <[1mDOWN[0m>, To continue now.



################################################################################
#==============================================================================#
################################################################################

Running MiSTer Downloader



################################################################################
#==============================================================================#
################################################################################

Running Arcade Organizer


FINISHED: Arcade Organizer


################################################################################
#==============================================================================#
################################################################################

Running Linux Update



################################################################################
#==============================================================================#
################################################################################

Update All 2.0 (5ec) by theypsilon. Run time: 0:00:38.81s at 2023-08-04 22:13:07
Commit: 5ecc39f

There were some errors in the Updaters.
Therefore, MiSTer hasn't been fully updated.

Check these logs from the Updaters that failed:
 - Scripts/.config/downloader/downloader.log

Maybe a network problem?
Check your connection and then run this script again.

Full log for more details: Scripts/.config/update_all/update_all.log


```

**Comment by aminta** [comment]
ok, I've deleted from "games/NEOGEO" the following files: `gog-broken-romsets.xml`, `gog-romsets.xml` and `romsets.xml` and now it works again!
