### ISSUE TITLE
script throwing a error regarding "dont_download.zip"

### ISSUE THREAD

**Issue by marceloMedeiros** [MiSTer-devel/Downloader_MiSTer#9]
The script is throwing this error...ive been trying to pinpoint if its something on my end, but i cant find anything here, so i decided to create this ticket.

Log:

/media/fat/Scripts# ./downloader.sh
Running MiSTer Downloader

START!

Reading file: ./downloader.ini
Reading default db

################################################################################
SECTION: distribution_mister

Downloading 5 files:
/tmp/cheats_folder_nes_summary.json.zip
/tmp/cheats_folder_sms_summary.json.zip
/tmp/global_filters_summary.json.zip
/tmp/global_shadow_masks_summary.json.zip
/tmp/mra_alternatives_summary.json.zip
*.....

Checking hashes...
+++++

Removing Filters/Composite Blend/Comp_Blend_HV_025.txt
Removing Filters/Composite Blend/Comp_Blend_HV_050.txt
Removing Filters/Composite Blend/Comp_Blend_HV_075.txt
Removing Filters/Composite Blend/Comp_Blend_H_025.txt
Removing Filters/Composite Blend/Comp_Blend_H_050.txt
Removing Filters/Composite Blend/Comp_Blend_H_075.txt
Removing Filters/Composite Blend/Comp_Blend_H_100.txt
Removing Filters/Composite Blend/Comp_Scan_HV_25.txt
Removing Filters/Composite Blend/Comp_Scan_HV_50.txt
Removing Filters/Composite Blend/Comp_Scan_HV_75.txt
Removing Filters/Composite Blend/Comp_Scan_H_025.txt
Removing Filters/Composite Blend/Comp_Scan_H_050.txt
Removing Filters/Composite Blend/Comp_Scan_H_075.txt
Removing Filters/Composite Blend/Comp_Scan_H_100.txt
Removing Filters/Hi Res Core Filters/2x_Scanlines_10.txt
Removing Filters/Hi Res Core Filters/2x_Scanlines_100.txt
Removing Filters/Hi Res Core Filters/2x_Scanlines_20.txt
Removing Filters/Hi Res Core Filters/2x_Scanlines_30.txt
Removing Filters/Hi Res Core Filters/2x_Scanlines_40.txt
Removing Filters/Hi Res Core Filters/2x_Scanlines_50.txt
Removing Filters/Hi Res Core Filters/2x_Scanlines_60.txt
Removing Filters/Hi Res Core Filters/2x_Scanlines_70.txt
Removing Filters/Hi Res Core Filters/2x_Scanlines_80.txt
Removing Filters/Hi Res Core Filters/2x_Scanlines_90.txt
Removing Filters/Hi Res Core Filters/HiRes_Gaussian_Sharp_01.txt
Removing Filters/Hi Res Core Filters/HiRes_Gaussian_Sharp_02.txt
Removing Filters/Hi Res Core Filters/HiRes_Gaussian_Sharp_03.txt
Removing Filters/Hi Res Core Filters/HiRes_Gaussian_Sharp_04.txt
Removing Filters/Hi Res Core Filters/HiRes_Gaussian_Sharp_05.txt
Removing Filters/Hi Res Core Filters/HiRes_Gaussian_Sharp_06.txt
Removing Filters/Hi Res Core Filters/HiRes_Gaussian_Sharp_07.txt
Removing Filters/LCD Color (Gameboy Color).txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type0_020.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type0_040.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type0_060.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type0_080.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type0_100.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type0_110.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type1_020.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type1_040.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type1_060.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type1_080.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type1_100.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type1_110.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type2_020.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type2_040.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type2_060.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type2_080.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type2_100.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type3_020.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type3_040.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type3_060.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type3_080.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type3_100.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type4_020.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type4_040.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type4_060.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type4_080.txt
Removing Filters/LCD Effects/Integer Scaling Effects/LCD_NN_Type4_100.txt
Removing Filters/LCD Effects/LCD_Effect_01.txt
Removing Filters/LCD Effects/LCD_Effect_02.txt
Removing Filters/LCD Effects/LCD_Effect_03.txt
Removing Filters/LCD Effects/LCD_Effect_04.txt
Removing Filters/LCD Effects/LCD_Effect_05.txt
Removing Filters/LCD Effects/LCD_Effect_06.txt
Removing Filters/LCD Effects/LCD_Effect_07.txt
Removing Filters/LCD Effects/LCD_Effect_08.txt
Removing Filters/LCD Effects/LCD_Effect_09.txt
Removing Filters/LCD Effects/LCD_Effect_Blur_00.txt
Removing Filters/LCD Effects/LCD_Effect_Blur_01.txt
Removing Filters/LCD Effects/LCD_Effect_Blur_02.txt
Removing Filters/LCD Effects/LCD_Effect_Blur_03.txt
Removing Filters/LCD Effects/LCD_Effect_Blur_04.txt
Removing Filters/LCD Effects/LCD_Effect_Br_01.txt
Removing Filters/LCD Effects/LCD_Effect_Br_02.txt
Removing Filters/LCD Monochrome (Gameboy).txt
Removing Filters/Misc/Horz Interpolation Only/Gaussian_Sharp_NN_04.txt
Removing Filters/Misc/Horz Interpolation Only/Gaussian_Sharp_NN_05.txt
Removing Filters/Misc/Horz Interpolation Only/Gaussian_Sharp_NN_06.txt
Removing Filters/Misc/Horz Interpolation Only/Gaussian_Sharp_NN_07.txt
Removing Filters/Misc/Nearest_Neighbor.txt
Removing Filters/Misc/Scanlines (Sharper)/Normal_Scanlines_010.txt
Removing Filters/Misc/Scanlines (Sharper)/Normal_Scanlines_015.txt
Removing Filters/Misc/Scanlines (Sharper)/Normal_Scanlines_020.txt
Removing Filters/Misc/Scanlines (Sharper)/Normal_Scanlines_025.txt
Removing Filters/Misc/Scanlines (Sharper)/Normal_Scanlines_030.txt
Removing Filters/Misc/Scanlines (Sharper)/Normal_Scanlines_040.txt
Removing Filters/Misc/Scanlines (Sharper)/Normal_Scanlines_050.txt
Removing Filters/Misc/Scanlines (Sharper)/Normal_Scanlines_060.txt
Removing Filters/Misc/Scanlines (Sharper)/Normal_Scanlines_070.txt
Removing Filters/Misc/Scanlines (Sharper)/Normal_Scanlines_080.txt
Removing Filters/Misc/Scanlines (Sharper)/Normal_Scanlines_090.txt
Removing Filters/Misc/Scanlines (Sharper)/Normal_Scanlines_100.txt
Removing Filters/Misc/Scanlines (Softer)/Catmull-Rom_Scanlines_010.txt
Removing Filters/Misc/Scanlines (Softer)/Catmull-Rom_Scanlines_015.txt
Removing Filters/Misc/Scanlines (Softer)/Catmull-Rom_Scanlines_020.txt
Removing Filters/Misc/Scanlines (Softer)/Catmull-Rom_Scanlines_025.txt
Removing Filters/Misc/Scanlines (Softer)/Catmull-Rom_Scanlines_030.txt
Removing Filters/Misc/Scanlines (Softer)/Catmull-Rom_Scanlines_040.txt
Removing Filters/Misc/Scanlines (Softer)/Catmull-Rom_Scanlines_050.txt
Removing Filters/Misc/Scanlines (Softer)/Catmull-Rom_Scanlines_060.txt
Removing Filters/Misc/Scanlines (Softer)/Catmull-Rom_Scanlines_070.txt
Removing Filters/Misc/Scanlines (Softer)/Catmull-Rom_Scanlines_080.txt
Removing Filters/Misc/Scanlines (Softer)/Catmull-Rom_Scanlines_090.txt
Removing Filters/Misc/Scanlines (Softer)/Catmull-Rom_Scanlines_100.txt
Removing Filters/Normal Upscaling/Bicubic.txt
Removing Filters/Normal Upscaling/Bilinear.txt
Removing Filters/Normal Upscaling/Gaussian_Sharp_01.txt
Removing Filters/Normal Upscaling/Gaussian_Sharp_02.txt
Removing Filters/Normal Upscaling/Gaussian_Sharp_03.txt
Removing Filters/Normal Upscaling/Gaussian_Sharp_04.txt
Removing Filters/Normal Upscaling/Gaussian_Sharp_05.txt
Removing Filters/Normal Upscaling/Gaussian_Sharp_06.txt
Removing Filters/Normal Upscaling/Gaussian_Sharp_07.txt
Removing Filters/Normal Upscaling/Lanczos2_10.txt
Removing Filters/Normal Upscaling/Lanczos2_12.txt
Removing Filters/Normal Upscaling/Lanczos2_15.txt
Removing Filters/Normal Upscaling/Lanczos3_10.txt
Removing Filters/Normal Upscaling/Lanczos3_12.txt
Removing Filters/Normal Upscaling/Lanczos3_15.txt
Removing Filters/Normal Upscaling/Lanczos_VIP.txt
Removing Filters/Normal Upscaling/Nearest_Neighbor.txt
Removing Filters/Normal Upscaling/bilinearsharp_01.txt
Removing Filters/Normal Upscaling/bilinearsharp_02.txt
Removing Filters/Normal Upscaling/bilinearsharp_03.txt
Removing Filters/Normal Upscaling/bilinearsharp_04.txt
Removing Filters/Normal Upscaling/bilinearsharp_05.txt
Removing Filters/Normal Upscaling/bilinearsharp_06.txt
Removing Filters/Normal Upscaling/bilinearsharp_07.txt
Removing Filters/Normal Upscaling/bilinearsharp_08.txt
Removing Filters/Normal Upscaling/bilinearsharp_09.txt
Removing Filters/Normal Upscaling/bilinearsharp_10.txt
Removing Filters/Normal Upscaling/bilinearsharp_11.txt
Removing Filters/Normal Upscaling/bilinearsharp_12.txt
Removing Filters/Normal Upscaling/bilinearsharp_13.txt
Removing Filters/Normal Upscaling/bilinearsharp_14.txt
Removing Filters/Normal Upscaling/bilinearsharp_15.txt
Removing Filters/Normal Upscaling/bilinearsharp_16.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_010_Sharp.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_010_Soft.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_020_Sharp.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_020_Soft.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_030_Sharp.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_030_Soft.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_040_Sharp.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_040_Soft.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_050_Sharp.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_050_Soft.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_060_Sharp.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_060_Soft.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_065_Sharp.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_065_Soft.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_070_Sharp.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_070_Soft.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_075_Sharp.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_075_Soft.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_080_Sharp.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_080_Soft.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_085_Sharp.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_085_Soft.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_090_Sharp.txt
Removing Filters/SNES Specific/Brightness 120%/SL_Br_120_090_Soft.txt
Removing Filters/SNES Specific/Misc (Bilinear Sharp)/SNES_bilinearsharp_01.txt
Removing Filters/SNES Specific/Misc (Bilinear Sharp)/SNES_bilinearsharp_02.txt
Removing Filters/SNES Specific/Misc (Bilinear Sharp)/SNES_bilinearsharp_03.txt
Removing Filters/SNES Specific/Misc (Bilinear Sharp)/SNES_bilinearsharp_04.txt
Removing Filters/SNES Specific/Misc (Bilinear Sharp)/SNES_bilinearsharp_05.txt
Removing Filters/SNES Specific/Misc (Bilinear Sharp)/SNES_bilinearsharp_06.txt
Removing Filters/SNES Specific/Misc (Bilinear Sharp)/SNES_bilinearsharp_07.txt
Removing Filters/SNES Specific/Misc (Bilinear Sharp)/SNES_bilinearsharp_08.txt
Removing Filters/SNES Specific/Misc (Bilinear Sharp)/SNES_bilinearsharp_09.txt
Removing Filters/SNES Specific/Misc (Bilinear Sharp)/SNES_bilinearsharp_10.txt
Removing Filters/SNES Specific/Misc (Bilinear Sharp)/SNES_bilinearsharp_11.txt
Removing Filters/SNES Specific/Misc (Bilinear Sharp)/SNES_bilinearsharp_12.txt
Removing Filters/SNES Specific/Misc (Bilinear Sharp)/SNES_bilinearsharp_13.txt
Removing Filters/SNES Specific/Misc (Bilinear Sharp)/SNES_bilinearsharp_14.txt
Removing Filters/SNES Specific/Misc (Bilinear Sharp)/SNES_bilinearsharp_15.txt
Removing Filters/SNES Specific/Misc (Bilinear Sharp)/SNES_bilinearsharp_16.txt
Removing Filters/SNES Specific/Misc (Gaussian Sharp)/SNES_Gaussian_Sharp_01.txt
Removing Filters/SNES Specific/Misc (Gaussian Sharp)/SNES_Gaussian_Sharp_02.txt
Removing Filters/SNES Specific/Misc (Gaussian Sharp)/SNES_Gaussian_Sharp_03.txt
Removing Filters/SNES Specific/Misc (Gaussian Sharp)/SNES_Gaussian_Sharp_04.txt
Removing Filters/SNES Specific/Misc (Gaussian Sharp)/SNES_Gaussian_Sharp_05.txt
Removing Filters/SNES Specific/Misc (Gaussian Sharp)/SNES_Gaussian_Sharp_06.txt
Removing Filters/SNES Specific/Misc (Gaussian Sharp)/SNES_Gaussian_Sharp_07.txt
Removing Filters/SNES Specific/Misc (Gaussian Sharp)/SNES_Gaussian_Sharp_NN_04.txt
Removing Filters/SNES Specific/Misc (Gaussian Sharp)/SNES_Gaussian_Sharp_NN_05.txt
Removing Filters/SNES Specific/Misc (Gaussian Sharp)/SNES_Gaussian_Sharp_NN_06.txt
Removing Filters/SNES Specific/Misc (Gaussian Sharp)/SNES_Gaussian_Sharp_NN_07.txt
Removing Filters/SNES Specific/No Interpolation.txt
Removing Filters/SNES Specific/SNES Interpolation (Sharp).txt
Removing Filters/SNES Specific/SNES Scanlines (Bright Sharp).txt
Removing Filters/SNES Specific/SNES Scanlines (Bright Soft).txt
Removing Filters/SNES Specific/SNES Scanlines (Sharp).txt
Removing Filters/SNES Specific/SNES Scanlines (Soft).txt
Removing Filters/Scanlines (Bright Sharp).txt
Removing Filters/Scanlines (Bright Soft).txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_010_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_010_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_020_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_020_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_030_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_030_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_040_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_040_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_050_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_050_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_060_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_060_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_065_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_065_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_070_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_070_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_075_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_075_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_080_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_080_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_085_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_085_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_090_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 110%/SL_Br_110_090_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_010_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_010_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_020_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_020_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_030_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_030_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_040_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_040_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_050_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_050_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_060_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_060_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_065_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_065_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_070_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_070_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_075_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_075_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_080_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_080_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_085_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_085_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_090_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 115%/SL_Br_115_090_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_010_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_010_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_020_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_020_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_030_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_030_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_040_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_040_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_050_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_050_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_060_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_060_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_065_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_065_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_070_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_070_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_075_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_075_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_080_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_080_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_085_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_085_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_090_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 120%/SL_Br_120_090_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_010_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_010_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_020_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_020_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_030_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_030_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_040_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_040_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_050_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_050_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_060_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_060_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_065_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_065_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_070_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_070_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_075_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_075_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_080_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_080_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_085_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_085_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_090_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 125%/SL_Br_125_090_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_010_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_010_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_020_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_020_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_030_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_030_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_040_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_040_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_050_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_050_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_060_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_060_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_065_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_065_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_070_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_070_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_075_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_075_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_080_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_080_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_085_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_085_Soft.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_090_Sharp.txt
Removing Filters/Scanlines (Bright)/Brightness 130%/SL_Br_130_090_Soft.txt
Removing Filters/Scanlines (Sharp).txt
Removing Filters/Scanlines (Soft).txt
Removing Filters/Scanlines (Vertical)/Vert_Normal_Scanlines_010.txt
Removing Filters/Scanlines (Vertical)/Vert_Normal_Scanlines_015.txt
Removing Filters/Scanlines (Vertical)/Vert_Normal_Scanlines_020.txt
Removing Filters/Scanlines (Vertical)/Vert_Normal_Scanlines_025.txt
Removing Filters/Scanlines (Vertical)/Vert_Normal_Scanlines_030.txt
Removing Filters/Scanlines (Vertical)/Vert_Normal_Scanlines_040.txt
Removing Filters/Scanlines (Vertical)/Vert_Normal_Scanlines_050.txt
Removing Filters/Scanlines (Vertical)/Vert_Normal_Scanlines_060.txt
Removing Filters/Scanlines (Vertical)/Vert_Normal_Scanlines_070.txt
Removing Filters/Scanlines (Vertical)/Vert_Normal_Scanlines_080.txt
Removing Filters/Scanlines (Vertical)/Vert_Normal_Scanlines_090.txt
Removing Filters/Scanlines (Vertical)/Vert_Normal_Scanlines_100.txt
Removing Filters/Vertical Scanlines (Sharp).txt
Removing Filters/Vertical Scanlines (Soft).txt
Removing _Computer/Minimig_20210705.rbf
Removing _Console/Genesis_20211214.rbf
Removing _Console/NeoGeo_20211214.rbf
Removing _Console/SNES_20211214.rbf
Removing _Console/TurboGrafx16_20211214.rbf
Removing Filters/CRT Simulation (Composite).txt
Removing Filters/CRT Simulation (S-Video).txt

Traceback (most recent call last):
  File "/tmp/dont_download.zip/downloader/main.py", line 34, in main
    exit_code = execute_full_run(env, logger)
  File "/tmp/dont_download.zip/downloader/main.py", line 46, in execute_full_run
    exit_code = runner.full_run()
  File "/tmp/dont_download.zip/downloader/full_run_service.py", line 69, in full_run
    self._online_importer.download_dbs_contents(importer_command, full_resync)
  File "/tmp/dont_download.zip/downloader/online_importer.py", line 53, in download_dbs_contents
    sub2.process_db_contents()
  File "/tmp/dont_download.zip/downloader/online_importer.py", line 208, in process_db_contents
    self._assert_valid_path(file_path)
  File "/tmp/dont_download.zip/downloader/online_importer.py", line 265, in _assert_valid_path
    raise InvalidDownloaderPath("Invalid path '%s', contact with the author of the database." % path)
downloader.online_importer.InvalidDownloaderPath: Invalid path '.gitattributes', contact with the author of the database.

Downloader failed!

**Comment by marceloMedeiros** [comment]
I tried running the script again today and it worked. Not sure what happened or if a new version was release since my last attempt, but everything seems to be working now, so im closing this.

Thanks!
